// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxqguvbqxmdqcwjybekk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4cWd1dmJxeG1kcWN3anliZWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjQxOTIsImV4cCI6MjA2ODk0MDE5Mn0.Dguf9eT1nWxFNKyvmtgntc1wiP3ri1kab-mDexGpvQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});